# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list_spec.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Spec(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QMainWindow\n"
"{\n"
" background-color:rgb(255, 228, 250)\n"
"}\n"
"QLabel\n"
"{\n"
"     font: 8pt \"Segoe Script\";\n"
"     color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton\n"
"{    \n"
"     font: 8pt \"Segoe Script\";\n"
"     background-color: rgb(255, 255, 255);\n"
"     border-style: outset;\n"
"     border-width: 3px;\n"
"     border-color: rgb(235, 235, 235);\n"
"     color: black;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(247, 214, 239);\n"
"    border-width: 2px;\n"
"    border-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(231, 200, 225);\n"
"    border-width: 2px;\n"
"    border-color: rgb(235, 235, 235);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 20, 301, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 441, 351))
        self.label_2.setObjectName("label_2")
        self.pushButton_list_spec = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_list_spec.setGeometry(QtCore.QRect(490, 420, 75, 23))
        self.pushButton_list_spec.setObjectName("pushButton_list_spec")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Список специальностей"))
        self.label.setText(_translate("MainWindow", "Специальности"))
        self.label_2.setText(_translate("MainWindow", "    01.03.01     Математика\n"
"    01.03.02    Прикладная математика и информатика\n"
"    03.03.02    Физика\n"
"    05.03.06    Экология и природопользование\n"
"    06.03.01    Биология\n"
"    08.03.01    Строительство\n"
"    09.03.01    Информатика и вычислительная техника\n"
"    09.03.02    Информационные системы и технологии\n"
"    09.03.03    Прикладная информатика\n"
"    12.03.01    Приборостроение\n"
"    15.03.01    Машиностроение\n"
"    16.03.03    Холодильная, криогенная техника и системы жизнеобеспечения\n"
"    21.03.02    Землеустройство и кадастры\n"
"    30.05.01    Медицинская биохимия\n"
"    30.05.02    Медицинская биофизика\n"
"    31.05.01    Лечебное дело\n"
"    37.03.01    Психология\n"
"    40.03.01    Юриспруденция\n"
"    40.05.01    Правовое обеспечение национальной безопасности\n"
"    40.05.03    Судебная экспертиза\n"
"    40.05.04    Судебная и прокурорская деятельность\n"
"    43.03.02    Туризм\n"
"    44.03.01    Педагогическое образование\n"
"    44.03.02    Психолого-педагогическое образование\n"
"    44.03.05    Педагогическое образование (с двумя профилями подготовки)"))
        self.pushButton_list_spec.setText(_translate("MainWindow", "Выход"))
