# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1234567, 123456))
        MainWindow.setStyleSheet("QMainWindow\n"
"{\n"
" border-image: url(C:/PyQt/pythonProject/site_page/fon.png)\n"
"}\n"
"QLabel\n"
"{\n"
"     font: 8pt \"Segoe Script\";\n"
"     color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton\n"
"{    \n"
"     font: 8pt \"Segoe Script\";\n"
"     background-color: rgb(255, 255, 255);\n"
"     border-style: outset;\n"
"     border-width: 3px;\n"
"     border-color: rgb(235, 235, 235);\n"
"     color: black;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(255, 235, 253);\n"
"    border-width: 2px;\n"
"    border-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(245, 218, 235);\n"
"    border-width: 2px;\n"
"    border-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"QComboBox\n"
"{    \n"
"     font: 8pt \"Segoe Script\";\n"
"     background-color: rgb(255, 255, 255);\n"
"     border-style: outset;\n"
"     border-width: 3px;\n"
"     border-color: rgb(235, 235, 235);\n"
"     color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"\n"
"{\n"
"      outline: none;\n"
"      border-color: rgb(235, 235, 235);\n"
"      selection-background-color: rgb(255, 235, 253);\n"
"      selection-color: rgb(155, 135, 153);\n"
"      font: 8pt \"Segoe Script\";\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover\n"
"{\n"
"    selection-background-color:rgb(255, 235, 253);\n"
"    border-width: 2px;\n"
"    color: black;\n"
"    border-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:pressed\n"
"{\n"
"    selection-background-color: rgb(245, 218, 235);\n"
"    border-width: 2px;\n"
"    color: black;\n"
"    border-color: rgb(235, 235, 235);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 251, 63))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(81, 61))
        self.label.setMaximumSize(QtCore.QSize(81, 61))
        self.label.setStyleSheet("QLabel\n"
"{\n"
"     border-image: url(C:/PyQt/pythonProject/site_page/logotip.png);\n"
"}\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(160, 30))
        self.label_2.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"     border-image: url(C:/PyQt/pythonProject/site_page/text.png);\n"
"}\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.result_entrance_label = QtWidgets.QLabel(self.centralwidget)
        self.result_entrance_label.setGeometry(QtCore.QRect(190, 390, 501, 20))
        self.result_entrance_label.setText("")
        self.result_entrance_label.setObjectName("result_entrance_label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 70, 81, 71))
        self.label_3.setMinimumSize(QtCore.QSize(81, 71))
        self.label_3.setMaximumSize(QtCore.QSize(81, 71))
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"     border-image: url(C:/PyQt/pythonProject/site_page/user7.png);\n"
"}\n"
"\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(360, 330, 139, 58))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem)
        self.login_push_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.login_push_button.setObjectName("login_push_button")
        self.horizontalLayout_5.addWidget(self.login_push_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.registration_push_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.registration_push_button.setObjectName("registration_push_button")
        self.verticalLayout_5.addWidget(self.registration_push_button)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(250, 160, 354, 158))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.password_text_edit = QtWidgets.QTextEdit(self.layoutWidget2)
        self.password_text_edit.setMinimumSize(QtCore.QSize(350, 20))
        self.password_text_edit.setMaximumSize(QtCore.QSize(350, 20))
        self.password_text_edit.setObjectName("password_text_edit")
        self.verticalLayout_3.addWidget(self.password_text_edit)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.login_text_edit = QtWidgets.QTextEdit(self.layoutWidget2)
        self.login_text_edit.setMinimumSize(QtCore.QSize(350, 20))
        self.login_text_edit.setMaximumSize(QtCore.QSize(350, 20))
        self.login_text_edit.setObjectName("login_text_edit")
        self.verticalLayout_2.addWidget(self.login_text_edit)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_push_button.setText(_translate("MainWindow", "Вход"))
        self.registration_push_button.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.label_4.setText(_translate("MainWindow", "Добро пожаловать! Рады видеть Вас снова!"))
        self.label_6.setText(_translate("MainWindow", "Password"))
        self.label_5.setText(_translate("MainWindow", "Login"))
